name: Verificação de Pull Request
on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
jobs:
  # Este workflow fecha PRs inválidos
  close-pr:
    name: closepr
    # O tipo de runner no qual o job será executado
    runs-on: ubuntu-latest
    permissions: write-all

    # Os passos representam uma sequência de tarefas que serão executadas como parte do job
    steps:
      - name: Fechar PR se a mensagem de commit contiver ".go"
        if: contains(github.event.pull_request.title, '.go')
        uses: superbrothers/close-pull-request@v3
        with:
          # Opcional. Postar um comentário na issue logo antes de fechar um pull request.
          comment: "PR inválido. Por favor, faça um `fork` e altere o seu próprio repositório, em vez de enviar alterações para o repositório principal. Se você tem certeza de que o seu PR tem como objetivo adicionar novas funcionalidades ou corrigir bugs no repositório principal, por favor altere o título padrão do PR. **Atenção**: Se você acionar este aviso novamente, isso poderá resultar no banimento da sua conta."

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Fazer checkout do código no diretório do módulo Go
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Organizar módulos
        run: |
          go mod tidy
          go generate ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          # Opcional: versão do golangci-lint a ser usada no formato v1.2 ou v1.2.3 ou `latest` para usar a versão mais recente
          version: v2.12.2
          args: ./cmd/music-dl ./core ./internal/... ./winres/...
          only-new-issues: true

          # Opcional: diretório de trabalho, útil para monorepos
          # working-directory: somedir

          # Opcional: argumentos de linha de comando do golangci-lint.
          # args: --issues-exit-code=0

          # Opcional: mostrar apenas novos problemas se for um pull request. O valor padrão é `false`.
          # only-new-issues: true

          # Opcional: se definido como true, a action não fará cache ou restaurará ~/go/pkg.
          # skip-pkg-cache: true

          # Opcional: se definido como true, a action não fará cache ou restaurará ~/.cache/go-build.
          # skip-build-cache: true
