name: Verificação de push de código
on:
  push:
    branches:
      - main
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Fazer checkout do código no diretório do módulo Go
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          submodules: 'recursive'

      - name: Organizar módulos
        run: |
          go mod tidy
          go generate ./...

      - name: Executar Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.12.2
          args: --new-from-rev=HEAD~1 ./cmd/music-dl ./core ./internal/... ./winres/...

      - name: Fazer commit das alterações
        if: ${{ !github.head_ref }}
        continue-on-error: true
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "chore(lint): Melhorar estilo de código"

      - name: Criar Pull Request
        if: ${{ !github.head_ref }}
        continue-on-error: true
        uses: peter-evans/create-pull-request@v8
        with:
          title: "chore(lint): Melhorar estilo de código"
